"""media

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-11 20:37:55.556446
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('uploader_ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('key', name=op.f('uq_media_key'))
    )
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index('ix_media_uploader_ip_created_at', 'media', ['uploader_ip', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_uploader_ip_created_at', table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
