"""catalog

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-12 05:56:18.298729
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], name=op.f('fk_products_cover_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('min_cm2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_cm2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('surcharge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('uv', 'engrave')", name=op.f('ck_price_tiers_method')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_tiers_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_tiers')),
    sa.UniqueConstraint('product_id', 'method', 'min_cm2', name=op.f('uq_price_tiers_product_id_method_min_cm2'))
    )
    op.create_index(op.f('ix_price_tiers_product_id'), 'price_tiers', ['product_id'], unique=False)
    op.create_table('shapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('dims', sa.JSON(), nullable=False),
    sa.Column('model_media_id', sa.String(length=36), nullable=True),
    sa.Column('model_transform', sa.JSON(), nullable=True),
    sa.Column('mm_per_unit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('cylinder', 'plane', 'disc', 'model')", name=op.f('ck_shapes_kind')),
    sa.CheckConstraint("status IN ('draft', 'ready')", name=op.f('ck_shapes_status')),
    sa.ForeignKeyConstraint(['model_media_id'], ['media.id'], name=op.f('fk_shapes_model_media_id_media'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_shapes_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shapes'))
    )
    op.create_index(op.f('ix_shapes_product_id'), 'shapes', ['product_id'], unique=False)
    op.create_table('print_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('anchor', sa.JSON(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=True),
    sa.Column('placement_note', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shape_id'], ['shapes.id'], name=op.f('fk_print_areas_shape_id_shapes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_areas')),
    sa.UniqueConstraint('shape_id', 'key', name=op.f('uq_print_areas_shape_id_key'))
    )
    op.create_index(op.f('ix_print_areas_shape_id'), 'print_areas', ['shape_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=False),
    sa.Column('material', sa.String(length=32), nullable=False),
    sa.Column('white_underbase', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("material IN ('ceramic_glossy', 'ceramic_matte', 'glass_clear', 'glass_frosted', 'fabric', 'paper', 'plastic', 'metal', 'wood')", name=op.f('ck_variants_material')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shape_id'], ['shapes.id'], name=op.f('fk_variants_shape_id_shapes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_variants_shape_id'), 'variants', ['shape_id'], unique=False)
    op.create_table('area_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('zone_x_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('zone_y_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('zone_w_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('zone_h_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_width_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_height_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_font_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('colors_allowed', sa.Boolean(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('uv', 'engrave')", name=op.f('ck_area_methods_method')),
    sa.ForeignKeyConstraint(['area_id'], ['print_areas.id'], name=op.f('fk_area_methods_area_id_print_areas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area_methods')),
    sa.UniqueConstraint('area_id', 'method', name=op.f('uq_area_methods_area_id_method'))
    )
    op.create_index(op.f('ix_area_methods_area_id'), 'area_methods', ['area_id'], unique=False)
    op.create_table('variant_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_colors_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_colors'))
    )
    op.create_index(op.f('ix_variant_colors_variant_id'), 'variant_colors', ['variant_id'], unique=False)
    op.create_table('catalog_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN product_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN variant_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN color_id IS NULL THEN 0 ELSE 1 END) = 1', name=op.f('ck_catalog_images_one_owner')),
    sa.ForeignKeyConstraint(['color_id'], ['variant_colors.id'], name=op.f('fk_catalog_images_color_id_variant_colors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_catalog_images_media_id_media'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_catalog_images_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_catalog_images_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_images'))
    )
    op.create_index(op.f('ix_catalog_images_color_id'), 'catalog_images', ['color_id'], unique=False)
    op.create_index(op.f('ix_catalog_images_product_id'), 'catalog_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalog_images_variant_id'), 'catalog_images', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_images_variant_id'), table_name='catalog_images')
    op.drop_index(op.f('ix_catalog_images_product_id'), table_name='catalog_images')
    op.drop_index(op.f('ix_catalog_images_color_id'), table_name='catalog_images')
    op.drop_table('catalog_images')
    op.drop_index(op.f('ix_variant_colors_variant_id'), table_name='variant_colors')
    op.drop_table('variant_colors')
    op.drop_index(op.f('ix_area_methods_area_id'), table_name='area_methods')
    op.drop_table('area_methods')
    op.drop_index(op.f('ix_variants_shape_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_print_areas_shape_id'), table_name='print_areas')
    op.drop_table('print_areas')
    op.drop_index(op.f('ix_shapes_product_id'), table_name='shapes')
    op.drop_table('shapes')
    op.drop_index(op.f('ix_price_tiers_product_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
