#!/bin/sh
# Xcode scheme pre-action (Runner.xcscheme > Build > Pre-actions): turns the
# --dart-define / --dart-define-from-file values Flutter puts into
# DART_DEFINES (base64 "KEY=value" entries, comma separated) into
# Flutter/DartDefines.xcconfig, which Debug/Release.xcconfig include:
#
#   GOOGLE_IOS_CLIENT_ID=<id>.apps.googleusercontent.com
#     -> GOOGLE_IOS_CLIENT_ID (Info.plist GIDClientID) and
#        GOOGLE_REVERSED_CLIENT_ID = com.googleusercontent.apps.<id>
#        (Info.plist URL scheme Google Sign-In returns to)
#   TELEGRAM_IOS_REDIRECT_URI (else TELEGRAM_REDIRECT_URI) = https://<host>...
#     -> TELEGRAM_LOGIN_HOST = <host>
#        (Runner.entitlements: applinks:<host>)
#
# Values missing from the defines keep the defaults in Debug/Release.xcconfig.
set -eu

SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT="$SRCROOT/Flutter/DartDefines.xcconfig"

decode() {
  printf '%s' "$1" | base64 --decode 2>/dev/null || printf '%s' "$1" | base64 -D 2>/dev/null || true
}

google_ios=""
tg_redirect=""
tg_ios_redirect=""

old_ifs=$IFS
IFS=','
for entry in ${DART_DEFINES:-}; do
  IFS=$old_ifs
  kv=$(decode "$entry")
  key=${kv%%=*}
  value=${kv#*=}
  case "$key" in
    GOOGLE_IOS_CLIENT_ID) google_ios=$value ;;
    TELEGRAM_REDIRECT_URI) tg_redirect=$value ;;
    TELEGRAM_IOS_REDIRECT_URI) tg_ios_redirect=$value ;;
  esac
  IFS=','
done
IFS=$old_ifs

{
  echo "// Generated by scripts/dart_defines_to_xcconfig.sh. Do not edit or commit."
  if [ -n "$google_ios" ]; then
    echo "GOOGLE_IOS_CLIENT_ID = $google_ios"
    echo "GOOGLE_REVERSED_CLIENT_ID = com.googleusercontent.apps.${google_ios%.apps.googleusercontent.com}"
  fi
  redirect=${tg_ios_redirect:-$tg_redirect}
  if [ -n "$redirect" ]; then
    host=$(printf '%s' "$redirect" | sed -E 's#^[a-zA-Z]+://##; s#[/?:].*$##')
    if [ -n "$host" ]; then echo "TELEGRAM_LOGIN_HOST = $host"; fi
  fi
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
